name: Build Linux
on:
  push:
    branches:
      - "build-artifacts-in-ci"

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ github.sha }}-${{ matrix.target }}
    strategy:
      matrix:
        target: [
          aarch64-unknown-linux-gnu,
          x86_64-unknown-linux-gnu,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install rust toolchain
      run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
        rustup target add ${{ matrix.target }}

    - name: Install protobuf compiler
      run: sudo apt-get install -y protobuf-compiler

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: libs

    - name: Build Breez 
      working-directory: libs/sdk-bindings
      env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-linux-gnu-gcc
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: sdk-bindings-${{ github.sha }}-${{ matrix.target }}
        path: libs/target/${{ matrix.target }}/release/libbreez_sdk_bindings.so
