name: Build Windows
on:
  push:
    branches:
      - "build-artifacts-in-ci"

jobs:
  build-windows:
    runs-on: windows-latest
    name: ${{ github.sha }}-${{ matrix.target }}
    strategy:
      matrix:
        target: [
          i686-pc-windows-msvc,
          x86_64-pc-windows-msvc,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install rust toolchain
      run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
        rustup target add ${{ matrix.target }}

    - name: Install protobuf compiler
      run: |
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-win64.zip -OutFile protoc-23.4-win64.zip
        Expand-Archive -Path protoc-23.4-win64.zip -DestinationPath .\protobuf
        dir .\protobuf\bin
        Add-Content $env:GITHUB_PATH "$((Get-Item .\protobuf\bin).FullName)"
      shell: powershell

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: libs

    - name: Build Breez 
      working-directory: libs/sdk-bindings
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: sdk-bindings-${{ github.sha }}-${{ matrix.target }}
        path: libs/target/${{ matrix.target }}/release/breez_sdk_bindings.dll
