name: Build Linux
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          aarch64-unknown-linux-gnu,
          x86_64-unknown-linux-gnu,
        ]
    steps:
    - name: check artifact exists
      uses: xSAVIKx/artifact-exists-action@v0
      id: check_artifact_exists
      with:
        name: sdk-bindings-${{ github.sha }}-${{ matrix.target }}

    - name: checkout
      if: steps.check_artifact_exists.outputs.exists == 'false'
      uses: actions/checkout@v3

    - name: Install rust toolchain
      if: steps.check_artifact_exists.outputs.exists == 'false'
      run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
        rustup target add ${{ matrix.target }}

    - name: Install protobuf compiler
      if: steps.check_artifact_exists.outputs.exists == 'false'
      run: sudo apt-get install -y protobuf-compiler

    - name: Install gcc-aarch64-linux-gnu
      if: |
        steps.check_artifact_exists.outputs.exists == 'false' &&
        matrix.target == 'aarch64-unknown-linux-gnu'
      run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu 

    - name: Install gcc-x86-64-linux-gnu
      if: |
        steps.check_artifact_exists.outputs.exists == 'false' &&
        matrix.target == 'x86_64-unknown-linux-gnu'
      run: sudo apt-get install -y gcc-x86-64-linux-gnu g++-x86-64-linux-gnu 

    - uses: Swatinem/rust-cache@v2
      if: steps.check_artifact_exists.outputs.exists == 'false'
      with:
        workspaces: libs

    - name: Build Breez 
      if: steps.check_artifact_exists.outputs.exists == 'false'
      working-directory: libs/sdk-bindings
      env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/aarch64-linux-gnu-gcc
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/x86_64-linux-gnu-gcc
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Archive release
      if: steps.check_artifact_exists.outputs.exists == 'false'
      uses: actions/upload-artifact@v3
      with:
        name: sdk-bindings-${{ github.sha }}-${{ matrix.target }}
        path: libs/target/${{ matrix.target }}/release/libbreez_sdk_bindings.so
