name: Publish Android Bindings
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'breez-sdk repo release (MAJOR.MINOR.PATCH)'
        required: true
        type: string

jobs:
  publish-android:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y protobuf-compiler
          cargo install --version 0.22.0 uniffi_bindgen
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.REPO_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - name: Build Android project
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.version }}
        run: |
          cd libs/sdk-bindings
          make init
          make bindings-android
      - name: Publish artifacts
        run: |
          cd libs/sdk-bindings/bindings-android
          ./gradlew publish -PlibraryVersion=${{ inputs.version }} -PbreezReposiliteUsername=${{ secrets.BREEZ_MVN_USERNAME }} -PbreezReposilitePassword=${{ secrets.BREEZ_MVN_PASSWORD }}
      - name: Trigger Jitpack Release
        run: |
          sleep 30
          curl -X DELETE -u${{ secrets.JITPACK_TOKEN }}: https://jitpack.io/api//builds/com.github.breez/breez-sdk/${{ inputs.version }} || true
          sleep 30
          curl -s -m 30 https://jitpack.io/com/breez/breez-sdk/${{ inputs.version }} || true
        shell: bash
